import Head from 'next/head';
import Jumbotron from '../components/organism/Jumbotron';
import Navbar from '../components/organism/Navbar';

const Home = () => {
  return (
    <>
      <Head>
        <title>Kuis Kuy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Jumbotron />
    </>
  );
};

export default Home;
